#!/usr/bin/env ruby
require "git-semforcer"

# Make sure we're not inside of .git
Dir.chdir("..") if ENV["GIT_DIR"] == "."

# Reopen STDIN for user response
$stdin.reopen(File.open("/dev/tty", "r"))

# Enforce our semver
GitSemforcer::Semver.new.enforce

# Little addon - update the Gemspec file
GitSemforcer::Gemspec.new.update
